name = "InsideOutNPF"
uuid = "0dfdc26d-a05e-4a70-a998-ef6d67ff522e"
authors = ["Sahel Mohammad Iqbal <sahel13miqbal@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
